import {
  BadgeCheck,
  Building2,
  CircleDollarSign,
  Home,
  KeyRound,
  MapPin,
  Scale,
  ShieldCheck,
  Store,
  TreePalm,
  UsersRound,
  Warehouse,
} from 'lucide-react';
import type { Agent, Category, Feature, Location, Property } from '@/lib/types';

const interiors = [
  'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1600563438938-a9a27216b4f5?auto=format&fit=crop&w=1200&q=80',
];

export const navLinks = [
  { label: 'Properties', href: '/properties' },
  { label: 'Categories', href: '/categories' },
  { label: 'Locations', href: '/locations' },
  { label: 'Agents', href: '/agents' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

export const features: Feature[] = [
  {
    title: 'Wide Range of Properties',
    description: 'We offer expert legal help for all related property items in Dubai.',
    icon: Building2,
  },
  {
    title: 'Buy or Rent Homes',
    description: 'We sell your home at the best market price and very quickly as well.',
    icon: Home,
  },
  {
    title: 'Trusted by Thousands',
    description: 'We offer you free consultancy to get a loan for your new home.',
    icon: ShieldCheck,
  },
];

export const agents: Agent[] = [
  {
    id: 'maya-rahman',
    name: 'Maya Rahman',
    specialty: 'Dubai Marina Specialist',
    bio: 'Maya guides waterfront buyers and renters through Marina, JBR, and Bluewaters properties with calm negotiation and sharp market context.',
    phone: '+971 455 8881',
    email: 'maya@justhome.ae',
    rating: 4.9,
    listingCount: 18,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    social: '@maya.justhome',
  },
  {
    id: 'omar-al-nuaimi',
    name: 'Omar Al Nuaimi',
    specialty: 'Villa Investment Advisor',
    bio: 'Omar works with families and investors searching for villas in Dubai Hills, Arabian Ranches, and Emirates Living.',
    phone: '+971 455 8882',
    email: 'omar@justhome.ae',
    rating: 4.8,
    listingCount: 21,
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80',
    social: '@omar.estates',
  },
  {
    id: 'leila-carter',
    name: 'Leila Carter',
    specialty: 'Luxury Leasing Consultant',
    bio: 'Leila curates premium leasing opportunities across Palm Jumeirah, Downtown Dubai, and Business Bay.',
    phone: '+971 455 8883',
    email: 'leila@justhome.ae',
    rating: 4.9,
    listingCount: 14,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
    social: '@leila.keys',
  },
  {
    id: 'daniel-wong',
    name: 'Daniel Wong',
    specialty: 'Commercial Property Lead',
    bio: 'Daniel supports founders and operators looking for offices, showrooms, and flexible commercial spaces.',
    phone: '+971 455 8884',
    email: 'daniel@justhome.ae',
    rating: 4.7,
    listingCount: 11,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    social: '@daniel.justhome',
  },
  {
    id: 'noura-hassan',
    name: 'Noura Hassan',
    specialty: 'Family Communities Advisor',
    bio: 'Noura helps families compare schools, commutes, amenities, and long-term value across green communities.',
    phone: '+971 455 8885',
    email: 'noura@justhome.ae',
    rating: 4.8,
    listingCount: 16,
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    social: '@noura.homes',
  },
  {
    id: 'samir-patel',
    name: 'Samir Patel',
    specialty: 'Off-Plan Project Consultant',
    bio: 'Samir evaluates new launches, payment plans, handover dates, and projected yields for long-view investors.',
    phone: '+971 455 8886',
    email: 'samir@justhome.ae',
    rating: 4.7,
    listingCount: 13,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    social: '@samir.properties',
  },
];

export const categories: Category[] = [
  {
    label: 'Apartment',
    slug: 'apartment',
    count: '22 Properties',
    description: 'Smart city homes near dining, transit, and business districts.',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80',
    icon: Building2,
  },
  {
    label: 'Villa',
    slug: 'villa',
    count: '14 Properties',
    description: 'Private residences with gardens, pools, and family-friendly plans.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    icon: Home,
  },
  {
    label: 'Town House',
    slug: 'town-house',
    count: '7 Properties',
    description: 'Connected communities with efficient layouts and shared amenities.',
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80',
    icon: Store,
  },
  {
    label: 'Penthouse',
    slug: 'penthouse',
    count: '9 Properties',
    description: 'Top-floor residences with dramatic views and premium finishes.',
    image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=80',
    icon: BadgeCheck,
  },
  {
    label: 'Commercial',
    slug: 'commercial',
    count: '8 Properties',
    description: 'Offices, showrooms, and high-visibility business addresses.',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',
    icon: Warehouse,
  },
  {
    label: 'Luxury Homes',
    slug: 'luxury-homes',
    count: '11 Properties',
    description: 'Signature homes with refined architecture and concierge-level living.',
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=900&q=80',
    icon: BadgeCheck,
  },
];

export const locations: Location[] = [
  {
    city: 'Dubai Marina',
    slug: 'dubai-marina',
    homes: '18 Properties',
    description: 'Waterfront towers, beach access, restaurants, and energetic nightlife.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'Downtown Dubai',
    slug: 'downtown-dubai',
    homes: '24 Properties',
    description: 'Iconic skyline living near the Burj Khalifa, DIFC, and Dubai Mall.',
    image: 'https://images.unsplash.com/photo-1534670007418-fbb7f6cf32c3?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'Palm Jumeirah',
    slug: 'palm-jumeirah',
    homes: '12 Properties',
    description: 'Resort living, sea views, private beaches, and luxury villas.',
    image: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'Dubai Hills',
    slug: 'dubai-hills',
    homes: '16 Properties',
    description: 'Green boulevards, golf views, schools, and spacious family homes.',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'Business Bay',
    slug: 'business-bay',
    homes: '15 Properties',
    description: 'Canal-side apartments with fast access to Downtown and Sheikh Zayed Road.',
    image: 'https://images.unsplash.com/photo-1524230572899-a752b3835840?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'Arabian Ranches',
    slug: 'arabian-ranches',
    homes: '10 Properties',
    description: 'Quiet villa communities, parks, schools, and established family living.',
    image: 'https://images.unsplash.com/photo-1600047508788-786f3865b4b0?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'Jumeirah Village Circle',
    slug: 'jumeirah-village-circle',
    homes: '20 Properties',
    description: 'Accessible apartments and townhouses with everyday community amenities.',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80',
  },
  {
    city: 'DIFC',
    slug: 'difc',
    homes: '8 Properties',
    description: 'Premium business district living close to finance, dining, and culture.',
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80',
  },
];

export const properties: Property[] = [
  {
    id: 'dubai-hills-family-home',
    title: 'Luxury Family Home in Dubai Hills',
    slug: 'dubai-hills-family-home',
    description: 'A warm, landscaped family villa with open living spaces, a private garden, and quick access to schools and Dubai Hills Mall.',
    location: 'Dubai Hills Estate, Dubai',
    city: 'Dubai Hills',
    address: 'Maple 3, Dubai Hills Estate, Dubai',
    price: '$1,250,000',
    priceValue: 1250000,
    status: 'FOR SALE',
    listingType: 'Buy',
    type: 'Villa',
    categorySlug: 'villa',
    featured: true,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', ...interiors],
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    beds: 4,
    baths: 3,
    sqft: '2,860',
    sqftValue: 2860,
    yearBuilt: 2021,
    parking: 2,
    amenities: ['Private garden', 'Community pool', 'Maid room', 'School nearby', 'Security'],
    agentId: 'omar-al-nuaimi',
    dateListed: '2026-06-02',
  },
  {
    id: 'marina-walk-apartment',
    title: 'Modern Apartment Near Marina Walk',
    slug: 'marina-walk-apartment',
    description: 'A bright rental apartment with balcony views, modern finishes, and walkable access to restaurants and the marina promenade.',
    location: 'Dubai Marina, Dubai',
    city: 'Dubai Marina',
    address: 'Marina Promenade, Dubai Marina, Dubai',
    price: '$4,800/mo',
    priceValue: 4800,
    status: 'FOR RENT',
    listingType: 'Rent',
    type: 'Apartment',
    categorySlug: 'apartment',
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80', ...interiors],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    beds: 2,
    baths: 2,
    sqft: '1,420',
    sqftValue: 1420,
    yearBuilt: 2020,
    parking: 1,
    amenities: ['Balcony', 'Gym', 'Pool', 'Concierge', 'Metro access'],
    agentId: 'maya-rahman',
    dateListed: '2026-06-13',
  },
  {
    id: 'palm-view-villa',
    title: 'Palm View Villa With Private Pool',
    slug: 'palm-view-villa',
    description: 'A premium Palm residence with sea-facing terraces, generous entertaining zones, and a private pool deck.',
    location: 'Palm Jumeirah, Dubai',
    city: 'Palm Jumeirah',
    address: 'Frond C, Palm Jumeirah, Dubai',
    price: '$2,950,000',
    priceValue: 2950000,
    status: 'FOR SALE',
    listingType: 'Buy',
    type: 'Luxury Homes',
    categorySlug: 'luxury-homes',
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80', ...interiors],
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    beds: 5,
    baths: 5,
    sqft: '4,710',
    sqftValue: 4710,
    yearBuilt: 2019,
    parking: 3,
    amenities: ['Private beach', 'Pool', 'Sea view', 'Smart home', 'Chef kitchen'],
    agentId: 'leila-carter',
    dateListed: '2026-05-28',
  },
  {
    id: 'arabian-ranches-townhouse',
    title: 'Bright Townhouse Close to Schools',
    slug: 'arabian-ranches-townhouse',
    description: 'A cheerful townhouse in a mature family community with nearby parks, schools, and weekend market access.',
    location: 'Arabian Ranches, Dubai',
    city: 'Arabian Ranches',
    address: 'Rasha, Arabian Ranches, Dubai',
    price: '$890,000',
    priceValue: 890000,
    status: 'FOR SALE',
    listingType: 'Buy',
    type: 'Town House',
    categorySlug: 'town-house',
    featured: true,
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80', ...interiors],
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80',
    beds: 3,
    baths: 3,
    sqft: '2,210',
    sqftValue: 2210,
    yearBuilt: 2018,
    parking: 2,
    amenities: ['Garden', 'Community park', 'Cycling track', 'Clubhouse', 'Security'],
    agentId: 'noura-hassan',
    dateListed: '2026-06-08',
  },
  {
    id: 'downtown-executive-residence',
    title: 'Executive Downtown Residence',
    slug: 'downtown-executive-residence',
    description: 'A refined high-floor rental residence with skyline views, hotel-style amenities, and fast DIFC access.',
    location: 'Downtown Dubai, Dubai',
    city: 'Downtown Dubai',
    address: 'Boulevard Heights, Downtown Dubai',
    price: '$7,200/mo',
    priceValue: 7200,
    status: 'FOR RENT',
    listingType: 'Rent',
    type: 'Apartment',
    categorySlug: 'apartment',
    images: ['https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80', ...interiors],
    image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80',
    beds: 3,
    baths: 2,
    sqft: '1,890',
    sqftValue: 1890,
    yearBuilt: 2022,
    parking: 2,
    amenities: ['Burj view', 'Concierge', 'Gym', 'Pool', 'Valet'],
    agentId: 'leila-carter',
    dateListed: '2026-06-17',
  },
  {
    id: 'business-bay-garden-suite',
    title: 'Garden Suite by the Canal',
    slug: 'business-bay-garden-suite',
    description: 'A calm canal-side home with a green terrace, efficient layout, and quick Downtown connectivity.',
    location: 'Business Bay, Dubai',
    city: 'Business Bay',
    address: 'Marasi Drive, Business Bay, Dubai',
    price: '$640,000',
    priceValue: 640000,
    status: 'FOR SALE',
    listingType: 'Buy',
    type: 'Apartment',
    categorySlug: 'apartment',
    images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80', ...interiors],
    image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80',
    beds: 2,
    baths: 2,
    sqft: '1,260',
    sqftValue: 1260,
    yearBuilt: 2021,
    parking: 1,
    amenities: ['Canal view', 'Terrace', 'Gym', 'Pool', 'Pet friendly'],
    agentId: 'maya-rahman',
    dateListed: '2026-05-22',
  },
];

const extraProperties: Property[] = [
  ['jvc-studio-loft', 'Compact Studio Loft in JVC', 'Jumeirah Village Circle', 'Jumeirah Village Circle', '$2,300/mo', 2300, 'FOR RENT', 'Rent', 'Apartment', 'apartment', 1, 1, '610', 610, 'samir-patel'],
  ['difc-corner-office', 'Furnished Corner Office in DIFC', 'DIFC', 'DIFC', '$1,420,000', 1420000, 'FOR SALE', 'Buy', 'Commercial', 'commercial', 0, 2, '1,940', 1940, 'daniel-wong'],
  ['dubai-hills-penthouse', 'Golf View Penthouse in Dubai Hills', 'Dubai Hills', 'Dubai Hills', '$2,180,000', 2180000, 'FOR SALE', 'Buy', 'Penthouse', 'penthouse', 4, 4, '3,120', 3120, 'omar-al-nuaimi'],
  ['marina-serviced-suite', 'Serviced Marina Suite With Balcony', 'Dubai Marina', 'Dubai Marina', '$5,650/mo', 5650, 'FOR RENT', 'Rent', 'Apartment', 'apartment', 2, 2, '1,180', 1180, 'maya-rahman'],
  ['ranches-courtyard-villa', 'Courtyard Villa Near Community Park', 'Arabian Ranches', 'Arabian Ranches', '$1,540,000', 1540000, 'FOR SALE', 'Buy', 'Villa', 'villa', 4, 4, '3,450', 3450, 'noura-hassan'],
  ['business-bay-showroom', 'Street-Level Showroom in Business Bay', 'Business Bay', 'Business Bay', '$9,800/mo', 9800, 'FOR RENT', 'Rent', 'Commercial', 'commercial', 0, 2, '2,400', 2400, 'daniel-wong'],
].map((item, index) => {
  const [id, title, location, city, price, priceValue, status, listingType, type, categorySlug, beds, baths, sqft, sqftValue, agentId] = item;
  const image = [
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600563438938-a9a27216b4f5?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
  ][index];

  return {
    id: String(id),
    title: String(title),
    slug: String(id),
    description: 'A carefully selected JustHome listing with strong location value, practical amenities, and clean move-in readiness.',
    location: `${location}, Dubai`,
    city: String(city),
    address: `${title}, ${location}, Dubai`,
    price: String(price),
    priceValue: Number(priceValue),
    status: status as Property['status'],
    listingType: listingType as Property['listingType'],
    type: type as Property['type'],
    categorySlug: String(categorySlug),
    featured: index % 2 === 0,
    images: [image, ...interiors],
    image,
    beds: Number(beds),
    baths: Number(baths),
    sqft: String(sqft),
    sqftValue: Number(sqftValue),
    yearBuilt: 2017 + index,
    parking: index % 3,
    amenities: ['Security', 'Gym', 'Covered parking', 'Concierge', 'Nearby retail'],
    agentId: String(agentId),
    dateListed: `2026-06-${String(10 + index).padStart(2, '0')}`,
  };
});

properties.push(...extraProperties);

export const stats = [
  { value: '5.2M', label: 'Owned from properties transactions' },
  { value: '7K+', label: 'Properties For Buy and Sell' },
  { value: '4.9', label: 'Average client rating' },
  { value: '114', label: 'Neighborhood specialists' },
];

export const serviceHighlights = [
  { label: 'Legal support', icon: Scale },
  { label: 'Loan consultancy', icon: CircleDollarSign },
  { label: 'Key handover', icon: KeyRound },
  { label: 'Prime locations', icon: MapPin },
  { label: 'Family living', icon: UsersRound },
  { label: 'Green communities', icon: TreePalm },
];

export const footerLinks = {
  Explore: ['Buy a Home', 'Rent a Home', 'Commercial', 'New Projects'],
  Company: ['About JustHome', 'Our Agents', 'Blog', 'Contact'],
  Support: ['Help Center', 'Mortgage Guide', 'Privacy Policy', 'Terms'],
};
